const {test}=require('node:test'),assert=require('node:assert/strict');
const {seed,validateState,calculate,retrieve,daysUntil,geometryAngles}=require('../core.cjs');
test('all eight subjects are editable starting records',()=>{const s=seed();assert.equal(s.subjects.length,8);assert.deepEqual(s.subjects.map(x=>x.name),['Math','English','Physics','Biology','Chemistry','Arabic','Islamic Studies','KSA Studies']);assert.equal(s.chats.length,0);assert.equal(s.sources.length,0);assert.equal(validateState(s),s)});
test('numerical verifier supports arithmetic and rejects executable expressions',()=>{assert.equal(calculate('sqrt(9)+2^3').result,11);assert.equal(calculate('sin(pi/2)').result,1);for(const bad of ['x=2','import("fs")','[1,2]','2^999999','1/0','sqrt(-1)'])assert.throws(()=>calculate(bad))});
test('retrieval remains inside selected sources and preserves page references',()=>{const s=seed();s.sources=[{id:'a',name:'Geometry',pages:[{page:1,text:'triangles and angles'},{page:2,text:'circles circumference'}]},{id:'b',name:'Other',pages:[{page:1,text:'triangles triangles'}]}];const rows=retrieve(s,['a'],'circumference');assert.equal(rows[0].page,2);assert.ok(rows.every(x=>x.sourceId==='a'))});
test('angles are calculated from positions rather than labels',()=>{const a=geometryAngles([{x:0,y:0},{x:1,y:0},{x:0,y:1}]);assert.ok(Math.abs(a[0]-90)<1e-10);assert.ok(Math.abs(a.reduce((x,y)=>x+y,0)-180)<1e-10)});
test('exam urgency uses Riyadh calendar date',()=>{assert.equal(daysUntil('2026-10-03',new Date('2026-10-02T22:00:00Z')),0);assert.equal(daysUntil('2026-10-04',new Date('2026-10-02T22:00:00Z')),1)});
test('invalid backups are rejected',()=>{assert.throws(()=>validateState({}));assert.throws(()=>validateState({...seed(),notes:null}))});
test('lesson page ranges and disabled sources constrain retrieval',()=>{const s=seed();s.sources=[{id:'a',name:'Book',ext:'.pdf',pages:[{page:1,text:'angles'},{page:2,text:'angles'},{page:3,text:'angles'}]},{id:'b',name:'Old',retired:true,pages:[{page:2,text:'angles'}]}];const rows=retrieve(s,['a','b'],'angles',{pageStart:2,pageEnd:2});assert.equal(rows.length,1);assert.equal(rows[0].page,2);assert.equal(rows[0].sourceId,'a')});
