const test=require('node:test'),assert=require('node:assert/strict'),{seed,validateState}=require('../core.cjs'),{request}=require('../practice-tests.cjs'),{parseQuestion,score}=require('../ui/practice-tests.js');
const valid={prompt:'Solve $2+2$.',options:['4','3','5','6'],answer:'A',explanation:'Add two and two.'};
test('practice question validation still rejects broken keys and duplicate options',()=>{assert.equal(parseQuestion(JSON.stringify(valid),'choice').answer,'A');assert.throws(()=>parseQuestion('{','choice'),/complete/);assert.throws(()=>parseQuestion(JSON.stringify({...valid,answer:'Z'}),'choice'),/invalid/);assert.throws(()=>parseQuestion(JSON.stringify({...valid,options:['4','4','5','6']}),'choice'),/invalid/)});
test('unsupported citations are removed without blocking otherwise valid questions',()=>{
 const pages=[{sourceId:'real',page:2}],out=parseQuestion(JSON.stringify({...valid,sourceId:'foreign',page:2,prompt:'Solve $2+2$. [[foreign:2]]',options:['4 [[real:99]]','3','5','6'],explanation:'Add two. [[real:2]] [[foreign:2]]'}),'choice',pages);
 assert.equal(out.citationWarning,true);assert.equal(out.sourceId,undefined);assert.equal(out.page,undefined);assert.ok(!JSON.stringify(out).includes('foreign'));assert.equal(out.options[0].text,'4');assert.equal(out.explanation,'Add two. [[real:2]]');assert.equal(out.answer,'A');assert.equal(pages.length,1);
 const wrongPage=parseQuestion(JSON.stringify({...valid,sourceId:'real',page:1}),'choice',pages);assert.equal(wrongPage.sourceId,undefined);assert.equal(wrongPage.citationWarning,true);
});
test('explicit supported citation pairs and numeric page strings normalize without guessing a source',()=>{
 const pages=[{sourceId:'real',page:2}];for(const [sourceId,page]of [['real',2],[' real ','2'],['[[real:2]]',1],['real:2',2]]){const out=parseQuestion(JSON.stringify({...valid,sourceId,page}),'choice',pages);assert.equal(out.sourceId,'real');assert.equal(out.page,2);assert.equal(out.citationWarning,undefined)}
 const noReference=parseQuestion(JSON.stringify(valid),'choice',pages);assert.equal(noReference.citationWarning,undefined);assert.equal(noReference.sourceId,undefined);assert.throws(()=>parseQuestion(JSON.stringify({...valid,prompt:'[[foreign:2]]'}),'choice',pages),/Invalid question/);
});
test('local question schemas constrain references to the actually provided source IDs and pages',()=>{
 const {schemaForPages,questionSchema}=require('../practice-tests.cjs'),schema=schemaForPages([{sourceId:'photo',page:1},{sourceId:'scan',page:3},{sourceId:'scan',page:4}]);assert.deepEqual(schema.properties.sourceId.enum,['','photo','scan']);assert.deepEqual(schema.properties.page.enum,[1,3,4]);assert.equal(questionSchema.properties.sourceId.enum,undefined);assert.deepEqual(schemaForPages([]).properties.sourceId.enum,['']);
});
test('scores use the selected answer key and distinguish unreviewed written work',()=>{const t={questions:[{id:'a',type:'choice',answer:'A'},{id:'b',type:'written',answer:'Because…'},{id:'c',type:'choice',answer:'C'}],answers:{a:'A',c:'D'},marks:{}};assert.deepEqual(score(t),{earned:1,reviewed:2,total:3,pending:1});t.marks.b=false;assert.deepEqual(score(t),{earned:1,reviewed:3,total:3,pending:0})});
test('test scope isolates subjects, follows lesson structure and retains older backups',()=>{const s=seed();delete s.practiceTests;validateState(s);assert.deepEqual(s.practiceTests,[]);const sub=s.subjects[2],id='source';s.sources.push({id,subjectId:s.subjects[0].id});s.lessons.push({id:'lesson',subjectId:sub.id,chapter:'Module 20',number:'1',title:'Motion'});const p={subjectId:sub.id,lessonId:'lesson',sourceIds:[id],count:3,type:'mixed',difficulty:'standard'};assert.equal(request(p,s,0).type,'choice');assert.equal(request(p,s,1).type,'written');assert.deepEqual(request(p,s,0).sourceIds,[]);assert.match(request(p,s,0).prompt,/Module 20 \/ Lesson 1 Motion/);assert.throws(()=>request({...p,count:200},s,0),/valid test/)});
