const {randomUUID}=require('node:crypto');
const math=require('mathjs');
const subjectDefs=[['Math','calculator','#4b775a'],['English','book-open','#9c7853'],['Physics','orbit','#567896'],['Biology','leaf','#71935e'],['Chemistry','flask-conical','#887399'],['Arabic','languages','#ad7855'],['Islamic Studies','book','#678679'],['KSA Studies','map','#987b58']];
function seed(){return {version:1,subjects:subjectDefs.map(([name,icon,color])=>({id:randomUUID(),name,icon,color})),lessons:[],chats:[],notes:[],sources:[],exams:[],attempts:[],settings:{aiMode:'chatgpt',backgroundUpdates:true,theme:'light',sound:true,sidebarWidth:244,tabs:['Tutor','Lessons','Notebook','Practice','Sources'],model:'',effort:'high',tutorLanguage:'English',dailyMinutes:45,maxOutputTokens:6000,monthlyTokenLimit:0},usage:{input:0,output:0,month:new Date().toISOString().slice(0,7)},ui:{subject:null,tab:'Tutor',chat:null,lesson:null}}}
function validateState(s){if(!s||s.version!==1||!Array.isArray(s.subjects)||!s.settings)throw new Error('This is not a supported Studora workspace.');for(const key of ['lessons','chats','notes','sources','exams','attempts'])if(!Array.isArray(s[key]))throw new Error('Incomplete workspace: '+key);if(s.subjects.length>200)throw new Error('Too many subjects.');return s}
function calculate(expression){if(typeof expression!=='string'||expression.length>300)throw new Error('Use a short numerical expression.');const node=math.parse(expression);let count=0;const funcs=new Set(['sqrt','sin','cos','tan','asin','acos','atan','abs','round','floor','ceil','log','exp','min','max','pow']);node.traverse(n=>{if(++count>100)throw new Error('Expression too complex.');if(!['OperatorNode','ConstantNode','ParenthesisNode','FunctionNode','SymbolNode'].includes(n.type))throw new Error('Only numerical calculations are supported.');if(n.type==='SymbolNode'&&!['pi','e',...funcs].includes(n.name))throw new Error('Unknown symbol.');if(n.type==='FunctionNode'&&!funcs.has(n.fn.name))throw new Error('Unsupported function.');if(n.type==='OperatorNode'&&!['+','-','*','/','^','%'].includes(n.op))throw new Error('Unsupported operator.');if(n.type==='OperatorNode'&&n.op==='^'&&n.args[1]?.isConstantNode&&Number(n.args[1].value)>1000)throw new Error('Exponent too large.');});const value=node.evaluate();if(typeof value!=='number'||!Number.isFinite(value))throw new Error('Result is not a finite real number.');return {expression,result:value,note:'Numerically evaluated; trigonometric functions use radians.'}}
function retrieve(s,ids,query,range={}){const terms=[...new Set((query.toLowerCase().match(/[\p{L}\p{N}]{2,}/gu)||[]).slice(0,60))];const pages=s.sources.filter(x=>ids.includes(x.id)&&!x.retired).flatMap(src=>(src.pages||[]).filter(p=>src.ext!=='.pdf'||(!range.pageStart||p.page>=range.pageStart)&&(!range.pageEnd||p.page<=range.pageEnd)).map(p=>({sourceId:src.id,name:src.name,page:p.page,text:p.text,score:terms.reduce((sum,t)=>sum+(p.text.toLowerCase().includes(t)?1:0),0)})));return pages.sort((a,b)=>b.score-a.score||a.page-b.page).slice(0,16).map(p=>({...p,text:p.text.slice(0,6500)}))}
function daysUntil(date,now=new Date()){const today=new Date(now.toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'})+'T00:00:00+03:00');const target=new Date(date+'T00:00:00+03:00');return Math.ceil((target-today)/86400000)}
function geometryAngles(points){return points.map((p,i)=>{const a=points[(i+1)%3],b=points[(i+2)%3],u=[a.x-p.x,a.y-p.y],v=[b.x-p.x,b.y-p.y];const l=Math.hypot(...u)*Math.hypot(...v);if(l<.00001)return null;return Math.acos(Math.max(-1,Math.min(1,(u[0]*v[0]+u[1]*v[1])/l)))*180/Math.PI})}
module.exports={seed,validateState,calculate,retrieve,daysUntil,geometryAngles};
