const {_electron:electron}=require('playwright'),path=require('node:path'),fs=require('node:fs/promises'),assert=require('node:assert/strict'),{seed}=require('../core.cjs');
(async()=>{
 const data=path.resolve(__dirname,'../../ai-test-'+Date.now()),state=seed();state.settings.sound=false;state.settings.model='gpt-3.5-turbo-instruct-0914';const math=state.subjects.find(s=>s.name==='Math');
 const sourceId='12345678-1234-1234-1234-123456789012',lessonId='lesson-geometry';
 state.sources.push({id:sourceId,subjectId:math.id,name:'Geometry textbook',ext:'.pdf',status:'ready',pages:[{page:1,text:'EXCLUDED PAGE'},{page:2,text:'Example 3: triangle angles total 180 degrees.'}]});
 state.lessons.push({id:lessonId,subjectId:math.id,chapter:'Chapter 2',number:'2.1',title:'Triangle angles',examples:['1','2','3','4'],sourceIds:[sourceId],pageStart:2,pageEnd:2});
 state.chats.push({id:'math-chat',subjectId:math.id,lessonId,title:'Geometry review',messages:[],sourceIds:[sourceId],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),draft:''});
 await fs.mkdir(data,{recursive:true});await fs.writeFile(path.join(data,'workspace.json'),JSON.stringify(state));
 const env={...process.env,STUDORA_TEST:'1',STUDORA_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;
 const app=await electron.launch({args:require('./test-env.cjs').args,env}),page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const settings=async()=>{await page.locator('.rail button[aria-label="Settings"]').click();await page.getByRole('heading',{name:'Make it yours',exact:true}).waitFor();};
 try{
  await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].show());await page.emulateMedia({reducedMotion:'reduce'});
  await app.evaluate(()=>{global.__apiRequests=[];global.__providerError=null;global.fetch=async(url,options)=>{const body=options?.body?JSON.parse(options.body):null;global.__apiRequests.push({url,body});const err=global.__providerError;if(err)return {ok:false,status:err.status,json:async()=>({error:err.error})};if(url.endsWith('/models'))return {ok:true,status:200,json:async()=>({data:[{id:'gpt-3.5-turbo-instruct-0914'},{id:'gpt-4.1-mini'},{id:'gpt-5'},{id:'gpt-4o-realtime-preview'}]})};return {ok:true,status:200,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'The angles add to 180 degrees.'}]}],usage:{input_tokens:10,output_tokens:4}})};};});
  // Disconnected tutoring stays inside Studora and retains the question.
  await page.locator('#subject-rail button[aria-label="Math"]').click();await page.locator('#example-select').selectOption('3');await page.locator('#prompt').fill('Explain Example 3 step by step');await page.getByRole('button',{name:'Send message',exact:true}).click();
  await page.locator('.error-inline').waitFor();assert.match(await page.locator('.error-inline').textContent(),/chat directly inside Studora/);assert.equal(await page.locator('#prompt').inputValue(),'Explain Example 3 step by step');assert.equal(await page.locator('[data-action="prepare-study"],[data-action="paste-chatgpt"]').count(),0);assert.equal(await page.locator('#modal').evaluate(d=>d.open),false);assert.equal(await app.evaluate(()=>global.__apiRequests.length),0);
  await settings();assert.equal(await page.locator('#ai-mode').inputValue(),'chatgpt');await page.locator('#ai-mode').selectOption('api');await page.getByRole('button',{name:'Connect API key',exact:true}).click();await page.locator('#api-key').fill('sk-test-local-disposable-not-a-real-key');await page.getByRole('button',{name:'Save connection',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#model-choice')?.options.length===3);assert.equal(await page.locator('#model-choice option').count(),3);
  assert.ok(!(await page.locator('#model-choice').textContent()).includes('instruct'));await page.locator('#model-choice').selectOption('gpt-4.1-mini');assert.equal(await page.locator('#reasoning').isDisabled(),true);
  await page.getByRole('button',{name:'Test selected model',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#connection-feedback').textContent.includes('Test passed'));let request=await app.evaluate(()=>global.__apiRequests.at(-1).body);assert.equal(request.model,'gpt-4.1-mini');assert.equal(request.reasoning,undefined);assert.equal(request.include,undefined);assert.equal(request.max_output_tokens,256);assert.ok(request.tools.length);assert.equal(request.input,'Reply with OK.');
  await page.locator('#subject-rail button[aria-label="Math"]').click();await page.locator('#prompt').fill('Explain the missing angle');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.message.assistant').length===1);request=await app.evaluate(()=>global.__apiRequests.at(-1).body);assert.equal(request.reasoning,undefined);assert.equal(request.model,'gpt-4.1-mini');
  await settings();await page.getByRole('button',{name:'Refresh available models',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#model-choice')?.options.length===3);await page.locator('#model-choice').selectOption('gpt-5');await page.getByRole('button',{name:'Test selected model',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#connection-feedback').textContent.includes('Test passed'));assert.equal(await app.evaluate(()=>global.__apiRequests.at(-1).body.reasoning.effort),'high');
  for(const err of [{status:404,error:{code:'model_not_found'},match:'cannot use gpt-5'},{status:429,error:{code:'insufficient_quota'},match:'Changing models will not resolve'},{status:401,error:{code:'invalid_api_key'},match:'rejected this API key'}]){
   await app.evaluate((_,err)=>{global.__providerError=err},err);await page.getByRole('button',{name:'Test selected model',exact:true}).click();await page.waitForFunction(text=>document.querySelector('#connection-feedback').textContent.includes(text),err.match);assert.ok(!(await page.locator('#connection-feedback').textContent()).includes('Error invoking remote'));
  }
  // Mock the already unit-tested OAuth manager; verify renderer orchestration with no browser login.
  await app.evaluate(()=>{global.__planCalls=[];const status={connected:true,enabled:true,persistent:true,active:'fixture-account',accounts:[{id:'fixture-account',email:'student@example.invalid',label:'Study account',signedIn:true}],firstWelcome:true};global.__studoraChatGPT.signIn=async()=>status;global.__studoraChatGPT.status=async()=>status;global.__studoraChatGPT.welcome=async()=>({...status,firstWelcome:false});global.__studoraChatGPT.request=async(endpoint,body)=>{global.__planCalls.push({endpoint,body});if(endpoint==='models')return {models:[{slug:'gpt-6.1-sol',display_name:'Account tutor',visibility:'list'},{slug:'hidden',visibility:'hide'}]};return {status:'completed',output:[{type:'message',content:[{type:'output_text',text:'An explanation using your ChatGPT plan.'}]}],usage:{input_tokens:10,output_tokens:4}}};});
  const paidBefore=await app.evaluate(()=>global.__apiRequests.length);await page.locator('#ai-mode').selectOption('chatgpt');await page.getByRole('button',{name:'Continue with ChatGPT',exact:true}).click();await page.getByRole('heading',{name:'You’re using your ChatGPT plan',exact:true}).waitFor();await page.getByRole('button',{name:'Got it',exact:true}).click();await page.locator('#model-choice').selectOption('gpt-6.1-sol');assert.match(await page.locator('#model-choice').textContent(),/Account tutor/);
  await page.locator('#subject-rail button[aria-label="Math"]').click();assert.match(await page.locator('.composer-footer').textContent(),/Using ChatGPT plan/);await page.locator('#prompt').fill('Explain the reasoning');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.message.assistant').length===2);assert.equal(await app.evaluate(()=>global.__apiRequests.length),paidBefore);
  await app.evaluate(()=>{global.__studoraChatGPT.request=async()=>{throw new Error('Your ChatGPT plan usage limit was reached.')}});await page.locator('#prompt').fill('Another question');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.locator('.error-inline').waitFor();assert.match(await page.locator('.error-inline').textContent(),/ChatGPT plan usage limit/);assert.equal(await app.evaluate(()=>global.__apiRequests.length),paidBefore);
  await page.waitForTimeout(400);const saved=await fs.readFile(path.join(data,'workspace.json'),'utf8');assert.ok(!saved.includes('sk-test'));assert.ok(!saved.includes('access_token'));assert.deepEqual(errors,[]);
  console.log('PASS: direct in-app tutoring, saved disconnected drafts, API compatibility and diagnostics, ChatGPT account models, and no paid fallback.');
 }finally{await app.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
