const {_electron:electron}=require('playwright'),path=require('node:path'),fs=require('node:fs/promises'),assert=require('node:assert/strict'),{seed}=require('../core.cjs');
(async()=>{
 const data=path.resolve(__dirname,'../../lessons-test-'+Date.now()),state=seed();state.settings.sound=false;state.settings.aiMode='api';state.settings.model='gpt-4.1-mini';
 const math=state.subjects.find(s=>s.name==='Math'),arabic=state.subjects.find(s=>s.name==='Arabic'),sourceId='fixture-source';
 // An older workspace has no structure settings; retain its lesson fields and source links.
 state.subjects.forEach(s=>delete s.lessonStructure);
 state.sources.push({id:sourceId,subjectId:arabic.id,name:'Arabic notes',ext:'.txt',status:'ready',pages:[{page:1,text:'المبتدأ والخبر'}]});
 state.lessons.push({id:'old-arabic',subjectId:arabic.id,chapter:'Chapter 2',number:'2.1',title:'المبتدأ والخبر',examples:['1','2'],sourceIds:[sourceId],pageStart:1,pageEnd:2});
 await fs.mkdir(data,{recursive:true});await fs.writeFile(path.join(data,'workspace.json'),JSON.stringify(state));
 const env={...process.env,STUDORA_TEST:'1',STUDORA_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;
 let app=await electron.launch({args:require('./test-env.cjs').args,env}),page=await app.firstWindow();const errors=[];
 const setup=async()=>{page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].show());await page.emulateMedia({reducedMotion:'reduce'});};
 const open=async name=>{await page.locator('#subject-rail button[aria-label="'+name+'"]').click();await page.getByRole('button',{name:'Lessons',exact:true}).click();};
 const add=async()=>page.locator('#main [data-action="add-lesson"]').first().click();
 const waitSaved=async predicate=>{const deadline=Date.now()+8000;while(Date.now()<deadline){const saved=await page.evaluate(()=>window.studora.load());if(predicate(saved))return;await new Promise(r=>setTimeout(r,50));}throw Error('Workspace save timed out.');};
 const save=async()=>{await page.getByRole('button',{name:'Save lesson',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);};
 try{
  await setup();await open('Math');await add();assert.equal(await page.locator('#f-examples').inputValue(),'');await page.getByLabel('Chapter',{exact:true}).fill('2');await page.getByLabel('Lesson number',{exact:true}).fill('2.1');await page.getByLabel('Lesson name',{exact:true}).fill('Triangle angles');await page.locator('#f-examples').fill('1, 2, 3, 4, 5');await save();assert.equal(await page.locator('.example-card').count(),5);assert.match(await page.locator('#sidebar').textContent(),/Chapter 2/);await page.locator('[data-action="learn-example"][data-example="5"]').click();assert.match(await page.locator('#prompt').inputValue(),/Example 5.*Chapter 2 \/ 2.1 Triangle angles/);
  for(const name of ['Physics','Biology','Chemistry']){await open(name);await add();assert.equal(await page.locator('#f-examples').count(),0);await page.getByLabel('Module',{exact:true}).fill('20');await page.getByLabel('Lesson number',{exact:true}).fill('1');await page.getByLabel('Lesson name',{exact:true}).fill(name+' concept');await save();assert.equal(await page.getByRole('heading',{name:'Worked examples',exact:true}).count(),0);assert.match(await page.locator('#sidebar').textContent(),new RegExp('Module 20.*Lesson 1 '+name+' concept'));await page.getByRole('button',{name:/Start learning/}).click();assert.match(await page.locator('.breadcrumb').textContent(),/Module 20 \/ Lesson 1/);assert.equal(await page.locator('#example-select').count(),0);}
  await open('Physics');await add();await page.getByLabel('Module',{exact:true}).fill('20');await page.getByLabel('Lesson number',{exact:true}).fill('2');await page.getByLabel('Lesson name',{exact:true}).fill('Second physics concept');await save();assert.equal(await page.locator('#sidebar .chapter-label').count(),1);assert.match(await page.locator('#sidebar').textContent(),/Lesson 2 Second physics concept/);
  await open('Arabic');await page.locator('#sidebar [data-action="lesson"]').click();assert.doesNotMatch(await page.locator('#sidebar').textContent(),/Chapter 2|2\.1|CHAPTERS/);await page.getByRole('button',{name:'Edit lesson',exact:true}).click();assert.equal(await page.locator('#f-chapter,#f-number,#f-examples').count(),0);assert.equal(await page.getByLabel('Lesson name',{exact:true}).inputValue(),'المبتدأ والخبر');assert.equal(await page.locator('[name="lesson-source"]:checked').count(),1);assert.equal(await page.locator('#f-page-end').inputValue(),'2');await save();
  await app.evaluate(()=>{global.__lessonRequests=[];global.fetch=async(url,opts)=>{global.__lessonRequests.push(JSON.parse(opts.body));return {ok:true,json:async()=>({output:[{type:'message',content:[{type:'output_text',text:'Fixture explanation'}]}]})};};});await page.evaluate(()=>window.studora.setKey('sk-local-fixture-not-a-real-key-1234'));await waitSaved(s=>s.ui.lesson==='old-arabic');await page.reload();await page.getByRole('button',{name:/Start learning/}).click();await page.locator('#prompt').fill('Explain this lesson');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.locator('.message.assistant').waitFor();const request=await app.evaluate(()=>global.__lessonRequests.at(-1));assert.match(request.instructions,/Current lesson: المبتدأ والخبر/);assert.match(request.instructions,/without invented numbers/);assert.doesNotMatch(request.instructions,/Chapter 2|2\.1/);
  await open('KSA Studies');await add();assert.equal(await page.locator('#f-chapter,#f-number,#f-examples').count(),0);await page.getByLabel('Lesson name',{exact:true}).fill('تأسيس المملكة');await save();assert.match(await page.locator('#sidebar').textContent(),/تأسيس المملكة/);
  // Switch this subject to a custom structure, then back, without losing lesson data.
  await page.getByRole('button',{name:'Lesson organization',exact:true}).click();await page.locator('#structure-preset').selectOption('modules');await page.locator('#f-group-label').fill('Unit');await page.locator('#structure-examples').check();await page.getByRole('button',{name:'Save organization',exact:true}).click();await page.getByRole('button',{name:'Edit lesson',exact:true}).click();await page.getByLabel('Unit',{exact:true}).fill('3');await page.getByLabel('Lesson number',{exact:true}).fill('2');await page.locator('#f-examples').fill('A, B');await save();assert.equal(await page.locator('.example-card').count(),2);
  await page.getByRole('button',{name:'Lesson organization',exact:true}).click();await page.locator('#structure-preset').selectOption('named');await page.getByRole('button',{name:'Save organization',exact:true}).click();assert.equal(await page.locator('.example-card').count(),0);assert.doesNotMatch(await page.locator('#sidebar').textContent(),/Unit 3|Lesson 2/);
  await waitSaved(s=>s.subjects.find(x=>x.name==='KSA Studies')?.lessonStructure?.preset==='named'&&s.lessons.some(l=>l.chapter==='Unit 3')); 
  const saved=await page.evaluate(()=>window.studora.load());const old=saved.lessons.find(l=>l.id==='old-arabic');assert.equal(old.chapter,'Chapter 2');assert.equal(old.number,'2.1');assert.deepEqual(old.examples,['1','2']);assert.deepEqual(old.sourceIds,[sourceId]);assert.equal(saved.lessons.find(l=>l.title==='تأسيس المملكة').chapter,'Unit 3');assert.equal(saved.lessons.find(l=>l.title==='تأسيس المملكة').number,'2');assert.ok(saved.chats.some(c=>c.subjectId===math.id));
  await page.screenshot({path:path.join(data,'named-lessons.png')});await app.close();app=await electron.launch({args:require('./test-env.cjs').args,env});page=await app.firstWindow();await page.getByRole('heading',{name:'Lessons',exact:true}).waitFor();assert.equal(await page.locator('.example-card').count(),0);assert.match(await page.locator('#sidebar').textContent(),/تأسيس المملكة/);assert.deepEqual(errors,[]);console.log('PASS: math examples, science modules, Arabic/KSA names, custom organization, AI context, existing data and restart persistence.');
 }catch(error){console.error('Fixture UI:',await page.locator('#main').textContent());console.error('Fixture data:',await app.evaluate(({app})=>app.getPath('userData')));throw error;}finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
