window.Geometry={mount(host,kind='triangle',onChange=()=>{},saved){
const points=saved?.points||[{x:105,y:235},{x:435,y:235},{x:290,y:70}];let mode=saved?.mode||'free',m=saved?.m??1,b=saved?.b??0;
const triangle=kind==='triangle';host.innerHTML=`<div class="geometry"><div class="geometry-head"><h3>${triangle?'Explore a triangle':'Explore a straight line'}</h3><span class="badge">Interactive exploration</span></div><svg class="diagram" viewBox="0 0 560 300" role="group" aria-label="${triangle?'Triangle with draggable vertices. Focus a vertex and use arrow keys to move it.':'Coordinate graph with adjustable slope and intercept.'}"></svg><div class="geo-footer"><div class="geo-controls">${triangle?'<label>Construction <select class="mode"><option value="free">Free triangle</option><option value="isosceles">Isosceles</option><option value="right">Right triangle</option></select></label><button class="reset secondary">Reset</button>':'<label>Slope m <input class="slope-range" type="range" min="-3" max="3" step="0.1" value="'+m+'"><output class="m-value"></output></label><label>Intercept b <input class="intercept-range" type="range" min="-3" max="3" step="0.1" value="'+b+'"><output class="b-value"></output></label>'}</div><div class="geo-status" aria-live="polite"></div></div></div>`;
const svg=host.querySelector('svg.diagram'),status=host.querySelector('.geo-status');const ns='http://www.w3.org/2000/svg';let dragging=-1;
function angle(p,a,b){const u=[a.x-p.x,a.y-p.y],v=[b.x-p.x,b.y-p.y],den=Math.hypot(...u)*Math.hypot(...v);return den?Math.acos(Math.max(-1,Math.min(1,(u[0]*v[0]+u[1]*v[1])/den)))*180/Math.PI:0}
function save(){onChange({points:points.map(p=>({...p})),mode,m,b})}
function constrain(){if(mode==='isosceles')points[2].x=(points[0].x+points[1].x)/2;if(mode==='right')points[2].x=points[0].x;points[1].y=points[0].y}
function draw(){const focus=svg.querySelector(':focus')?.dataset.point;let grid='';for(let x=30;x<560;x+=50)grid+=`<path class="geo-grid" d="M${x} 15V285"/>`;for(let y=25;y<300;y+=50)grid+=`<path class="geo-grid" d="M15 ${y}H545"/>`;if(triangle){const angles=points.map((p,i)=>angle(p,points[(i+1)%3],points[(i+2)%3]));const area=Math.abs((points[1].x-points[0].x)*(points[2].y-points[0].y)-(points[2].x-points[0].x)*(points[1].y-points[0].y))/2;svg.innerHTML=grid+`<polygon class="geo-shape" points="${points.map(p=>`${p.x},${p.y}`).join(' ')}"/>`+points.map((p,i)=>`<circle class="geo-point" data-point="${i}" cx="${p.x}" cy="${p.y}" r="7" tabindex="0" role="button" aria-label="Vertex ${'ABC'[i]}, ${angles[i].toFixed(1)} degrees. Use arrow keys to move."/><text class="geo-label" x="${p.x+12}" y="${p.y-12}">${'ABC'[i]}</text><text class="geo-measure" x="${p.x+12}" y="${p.y+18}">${angles[i].toFixed(1)}°</text>`).join('');status.textContent=area<50?'These points are nearly collinear. Move a vertex to form a triangle.':`∠A ${angles[0].toFixed(1)}° + ∠B ${angles[1].toFixed(1)}° + ∠C ${angles[2].toFixed(1)}° = ${angles.reduce((a,b)=>a+b,0).toFixed(1)}°. Measurements illustrate the relationship; they are not a proof.`;}else{const line=[];for(let x=-5;x<=5;x+=.02){const px=280+x*45,py=150-(m*x+b)*40;if(py>=15&&py<=285)line.push((line.length?'L':'M')+px.toFixed(1)+' '+py.toFixed(1))}svg.innerHTML=grid+`<path class="geo-grid" style="stroke:var(--muted)" d="M15 150H545M280 15V285"/><path class="geo-shape" style="fill:none" d="${line.join(' ')}"/><text class="geo-label" x="526" y="170">x</text><text class="geo-label" x="292" y="28">y</text><text class="geo-measure" x="262" y="170">0</text>`;host.querySelector('.m-value').textContent=m.toFixed(1);host.querySelector('.b-value').textContent=b.toFixed(1);status.textContent=`y = ${m.toFixed(1)}x ${b<0?'−':'+'} ${Math.abs(b).toFixed(1)}. For each increase of 1 in x, y changes by ${m.toFixed(1)}.`}if(focus!==undefined)svg.querySelector(`[data-point="${focus}"]`)?.focus();}
function move(i,x,y){points[i]={x:Math.max(30,Math.min(525,x)),y:Math.max(35,Math.min(265,y))};if(mode!=='free'){if(i<2){const base=points[i].y;points[0].y=points[1].y=base;points[0].x=Math.min(points[0].x,points[1].x-35);}constrain()}draw();save()}
svg.addEventListener('pointerdown',e=>{if(e.target.dataset.point!==undefined){dragging=Number(e.target.dataset.point);svg.setPointerCapture(e.pointerId)}});svg.addEventListener('pointermove',e=>{if(dragging<0)return;const matrix=svg.getScreenCTM();if(!matrix)return;const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());move(dragging,pt.x,pt.y)});svg.addEventListener('pointerup',()=>dragging=-1);svg.addEventListener('pointercancel',()=>dragging=-1);svg.addEventListener('keydown',e=>{const i=Number(e.target.dataset.point);if(!Number.isInteger(i)||!e.target.hasAttribute('data-point'))return;const d={ArrowLeft:[-5,0],ArrowRight:[5,0],ArrowUp:[0,-5],ArrowDown:[0,5]}[e.key];if(d){e.preventDefault();move(i,points[i].x+d[0],points[i].y+d[1])}});
if(triangle){const select=host.querySelector('.mode');select.value=mode;select.onchange=()=>{mode=select.value;if(mode!=='free')constrain();draw();save()};host.querySelector('.reset').onclick=()=>{points.splice(0,3,{x:105,y:235},{x:435,y:235},{x:290,y:70});if(mode!=='free')constrain();draw();save()};}else{host.querySelector('.slope-range').oninput=e=>{m=Number(e.target.value);draw();save()};host.querySelector('.intercept-range').oninput=e=>{b=Number(e.target.value);draw();save()};}draw();return{snapshot:()=>({points,mode,m,b})};
}};
